# Generated by Django 3.0.8 on 2020-07-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usermodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_picture',
            field=models.ImageField(default='accounts/profile_pics/default.jpg', upload_to='accounts/profile_pics/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
