# Generated by Django 3.0.8 on 2020-07-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200723_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
